name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1
    - name: Install modules
      run: bun install
    - name: Run ESLint
      run: bun run lint
